version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: store_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: storedb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apassword
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    image: nathalyr15/proyecto-store-app:latest
    container_name: store_app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: storedb
      DB_USERNAME: appuser
      DB_PASSWORD: apassword
      APP_ENV: production
      APP_DEBUG: 'false'
    depends_on:
      - db
    volumes:
      - app_storage:/var/www/html/storage
    restart: unless-stopped

  backend_nginx:
    image: nginx:stable-alpine
    container_name: store_nginx
    depends_on:
      - app
    # NO exponer puertos en el host: backend accesible solo internamente
    # Si necesitas pruebas directas, puedes mapear a otro puerto (ej. "8081:80")
    restart: unless-stopped

  frontend:
    image: nathalyr15/proyecto-store-frontend:latest
    container_name: store_frontend
    depends_on:
      - backend_nginx
    ports:
      - "8080:80"   # expone la app al host en 8080 (traefik ya usa 80/443)
    restart: unless-stopped

volumes:
  db_data:
  app_storage:
