services:
  web:
    image: nathalyr15/proyecto-store:latest
    container_name: proyecto-store
    ports:
      - "8080:80"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: storedb
      DB_USERNAME: appuser
      DB_PASSWORD: apassword
      RUN_MIGRATIONS: "false"
    depends_on:
      - db
    volumes:
      - ./Proyecto/Backend/back:/var/www/html      # <--- monta el backend completo
      - ./storage:/var/www/html/storage            # opcional: mantener storage externo


  db:
    image: mysql:8.0
    container_name: proyecto-store-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: storedb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db-data:
