version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: store_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: storedb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apassword
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    image: nathalyr15/proyecto-store-app:latest
    container_name: store_app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: storedb
      DB_USERNAME: appuser
      DB_PASSWORD: apassword
      APP_ENV: production
      APP_DEBUG: 'false'
    depends_on:
      - db
    volumes:
      - app_storage:/var/www/html/storage
    restart: unless-stopped

  backend_nginx:
    image: nginx:stable-alpine
    container_name: store_nginx
    depends_on:
      - app
    volumes:
    - ./backend/default.conf:/etc/nginx/conf.d/default.conf:ro
    - app_storage:/var/www/html/storage
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.store_nginx.rule=Host(`api.storeproyect.shop`)"
      - "traefik.http.routers.store_nginx.entrypoints=websecure"
      - "traefik.http.routers.store_nginx.tls=true"
      - "traefik.http.routers.store_nginx.tls.certresolver=letsencrypt"   # <- AHORA
      - "traefik.http.services.store_nginx.loadbalancer.server.port=80"
    restart: unless-stopped

  frontend:
    image: nathalyr15/proyecto-store-frontend:latest
    container_name: store_frontend
    depends_on:
      - backend_nginx
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.store_frontend.rule=Host(`storeproyect.shop`)"
      - "traefik.http.routers.store_frontend.entrypoints=websecure"
      - "traefik.http.routers.store_frontend.tls=true"
      - "traefik.http.routers.store_frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.store_frontend.loadbalancer.server.port=80"
    restart: unless-stopped

volumes:
  db_data:
  app_storage:
